### ISSUE TITLE
omz测试！问题！

### ISSUE THREAD

**Issue by wangmings** [yaocccc/omz#2]
# omz测试

## 测试平台
> mac iTerm2终端
> 测试对比: omz: zsh启动时间: 0.098
> 测试对比: oh my zsh: zsh启动时间: 0.12
> 通过测试感觉没快多少！

## omz优点
> 代码少！方便修改使用

## omz缺点
> 在安装所有依赖后，无法使用图片预览，或者某些功能无法使用，
> 有可能是我使用的平台或者终端不支持吧!

## 帮助
> 有知道的，请说明，帮助一下？

**Comment by yaocccc** [comment]
> 

item2无法预览是吧，我有时间会更新一下。目前没特地未它做适配

**Comment by wangmings** [comment]
# 感谢回复！期待你的下一个版本!
