### ISSUE TITLE
omz TAB键选择背景颜色，字体颜色的修改

### ISSUE THREAD

**Issue by wangmings** [yaocccc/omz#3]
# omz TAB键选择背景颜色，字体颜色的修改

## 示例
![截屏2023-01-24 下午3 01 00](https://user-images.githubusercontent.com/44308153/214231166-fb557680-cdfa-47ce-a1a8-a75863916ca1.png)

> 当按下tab键，进入选择模式后！有些字体，背景，颜色，不适用，需要进行修改，应该修改那个文件的代码来修改字体颜色或者背景颜色

## 有知道的，提供一下帮助！

**Comment by yaocccc** [comment]
> # omz TAB键选择背景颜色，字体颜色的修改
> ## 示例
> ![截屏2023-01-24 下午3 01 00](https://user-images.githubusercontent.com/44308153/214231166-fb557680-cdfa-47ce-a1a8-a75863916ca1.png)
> 
> > 当按下tab键，进入选择模式后！有些字体，背景，颜色，不适用，需要进行修改，应该修改那个文件的代码来修改字体颜色或者背景颜色
> 
> ## 有知道的，提供一下帮助！

omz的代码里是 config/fzf.zsh, FZF_DEFAULT_OPTS这一行。

你可以man fzf，来查看如何配置颜色，然后可以在你自己的配置中。覆盖掉 export FZF_DEFAULT_OPTS

**Comment by yaocccc** [comment]
注意个人的export FZF_DEFAULT_OPTS一定要在omz加载之后完成

**Comment by wangmings** [comment]
> 我刚才查看了一下，好像，并没有那么简单，config/fzf.zsh, FZF_DEFAULT_OPTS这一行，好像并没有修改颜色的字段，是不是应该修改插件目录下的fzf-tab目录下的文件，但是，我看了一下，代码太多了，没有还没有找到！

我百度了一下fzf,但是，还是教程还是比较模糊
![截屏2023-01-24 下午3 38 37](https://user-images.githubusercontent.com/44308153/214236477-ad9d415e-1961-4bd0-a544-b3ceeadba3c0.png)

**Comment by wangmings** [comment]
我在研究一下把
